import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NavigationProvider } from '../contexts/UserContext';
import Header from "../components/layouts/header/header";
import Footer from "../components/layouts/footer/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="JA">
      <NavigationProvider>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </NavigationProvider>
    </html>
  );
}
