import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/layouts/header/header";
import Footer from "../components/layouts/footer/footer";
import Navigation from "../components/layouts/navigation/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="JA">
      <body> 
        <Header />
            {children}
        <Footer />
      </body>
    </html>
  );
}
